# docker-compose.yml (Revised)
services:
  build:
    build:
      context: .
      # BUILD_TARGET is now passed as env var, not build arg
    working_dir: /app
    environment:
      # Pass BUILD_TARGET as an environment variable
      - BUILD_TARGET=${BUILD_TARGET:-build:all} # Default build target
      # Add any other build-time env vars here if needed
      # e.g., - NODE_ENV=production
    volumes:
      # Mount source code (Docker uses .dockerignore here)
      - .:/app
      # Use a named volume for node_modules isolation
      - node_modules:/app/node_modules
      # Map container output dirs back to host
      - ./dist:/app/dist
      - ./dist-electron:/app/dist-electron

# Define the named volume for node_modules cache/isolation
volumes:
  node_modules:
