name: Cross-Compile and Publish Binaries

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Cross-compile binaries
        run: bun cross-compile

      - name: Upload binaries to release
        if: github.event_name == 'release'  # Only runs for release events
        uses: softprops/action-gh-release@v2
        with:
          files: out/tweet-chat-*